### ISSUE TITLE
updated_at not being updated (Timestamping)

### ISSUE THREAD

**Issue by lucaspiller** [sinefunc/ohm-contrib#1]
There is bug in the Timestamping extension causing the updated_at attribute to not be updated on subsequent saves:

This should be changed to:
    self.updated_at ||= Time.now.utc

this:
    self.updated_at = Time.now.utc

I'm guessing this was done to enable passing updated_at as a parameter, however it doesn't automatically update.

http://github.com/sinefunc/ohm-contrib/blob/master/lib/ohm/contrib/timestamping.rb#L32

**Comment by cyx** [comment]
Very good catch. Thanks fixing.

**Comment by cyx** [comment]
Fixed as of 0.0.27
